server:
   port: 9001
spring:
    application:
       name: lottery-member-service
    datasource:
       driver-class-name: org.h2.Driver
       url: jdbc:h2:~/test
       username: sa
       max-active: 10
       max-idle: 5
       min-idle: 0
       schema: classpath:sql/member_ddl.sql #创建数据库
       data: classpath:sql/data.sql #插入测试数据
    h2:
      console:
        enabled: true
        path: /h2
mybatis:
   mapper-locations: classpath:/mybatis/*Mapper.xml
   type-aliases-package: com.codedak.entity
   
logging:
   level:
      root: info
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.118.206.130:9511/eureka/,
