server:
  port: 8001
spring:
  application:
    name: lottery-member
logging:
   level:
      root: info
      

        
eureka: 
  instance: 
    prefer-ip-address: true
  client:
    serviceUrl:   #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://127.0.0.1:9511/eureka/